name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [arm64, x64, x86]
        
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Publish
        run: >- 
          dotnet publish 
          -c Release 
          -r win-${{ matrix.platform }} 
          --self-contained true
          /t:Publish
          -p:WindowsPackageType=None
          -p:SelfContained=true
          -p:WindowsAppSDKSelfContained=true
          -p:PublishSingleFile=true
          -p:WindowsPackageType=None
          -p:Platform=${{ matrix.platform }} 
          -p:RuntimeIdentifier=win-${{ matrix.platform }} 
          -p:Configuration=Release
          -p:TargetFramework=net8.0-windows10.0.22621.0
          -p:PublishTrimmed=false
          -p:DebugType=embedded
          -p:PublishProtocol=FileSystem

      - name: Upload MSIX package
        uses: actions/upload-artifact@v4
        with:
          name: MSIX Package-${{ matrix.platform }}
          path: ${{ github.workspace }}\TestWinuiRep\bin
