name: Upload dotnet package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [arm64, x64, x86]
        
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore --arch ${{ matrix.platform }}
        
#      - name: Build
#        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish -r win-${{ matrix.platform }} -c ${{ matrix.configuration }} -p:PublishProfile=win-${{ matrix.platform }}

      - name: Upload MSIX package
        uses: actions/upload-artifact@v4.3.0
        with:
          name: MSIX Package-${{ matrix.platform }}
          path: ${{ github.workspace }}\TestWinuiRep\\bin
